######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 4 17:52:30 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = testqstring
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testqstring.cpp

QMAKE_CXXFLAGS += -g -Wall -fprofile-arcs -ftest-coverage -O0
QMAKE_LFLAGS += -g -Wall -fprofile-arcs -ftest-coverage  -O0
LIBS += -lgcov
