######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 4 20:56:59 2016
######################################################################

TEMPLATE = app
TARGET = hello
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += test1.h test2.h
SOURCES += test1.cpp tst_ut_template_1test.cpp

QT += testlib

QMAKE_CXXFLAGS += -g -Wall -fprofile-arcs -ftest-coverage -O0

QMAKE_LFLAGS += -g -Wall -fprofile-arcs -ftest-coverage  -O0

LIBS += -lgcov
